-- autocmd("BufEnter", function()
--   vim.schedule(function()
--     local map = vim.keymap.set
--     local prefix = "<leader>"
--
--     for i = 1, 9 do
--       map("n", prefix .. i, function()
--         require("fish.espeto").go(i)
--       end, { desc = "Go to file " .. i })
--     end
--
--     for i = 1, 9 do
--       map("n", prefix .. "h" .. i, function()
--         local buf = vim.api.nvim_get_current_buf()
--         local path = vim.api.nvim_buf_get_name(buf)
--         if path == "" then
--           vim.notify("No File", vim.log.levels.ERROR)
--           return
--         end
--         require("fish.espeto").set(i, path)
--       end, { desc = "Espeto: add file in " .. i })
--     end
--
--     for i = 1, 9 do
--       map("n", prefix .. "hd" .. i, function()
--         require("fish.espeto").remove(i)
--       end, { desc = "Espeto: delete file in " .. i })
--     end
--
--     map("n", prefix .. "he", require("fish.espeto").list, { desc = "Espeto: list files" })
--
--     map("n", prefix .. "ha", function()
--       local buf = vim.api.nvim_get_current_buf()
--       local path = vim.api.nvim_buf_get_name(buf)
--       if path == "" then
--         vim.notify("Buffer sem nome", vim.log.levels.ERROR)
--         return
--       end
--       require("fish.espeto").add(path)
--     end, { desc = "Espeto: add file" })
--
--     require("fish.espeto").load()
--   end)
-- end)
