vim.schedule(function()
vim.cmd.packadd("fzf-lua")
local Fzf = require("fzf-lua")
Fzf.setup({
	"ivy",
  ui_select = true,
	fzf_colors = {
		true, -- inherit fzf colors that aren't specified below from
	},
})

vim.keymap.set("n", "z=", ":FzfLua spell_suggest<Cr>")

vim.keymap.set("n", "<M-o>", "<Cmd>FzfLua files<Cr>", { desc = "Find" })
vim.keymap.set("n", "<M-s>", "<Cmd>FzfLua live_grep<Cr>", { desc = "Grep" })
vim.keymap.set("n", "<M-h>", "<Cmd>FzfLua buffers<Cr>", { desc = "Buffers" })
vim.keymap.set("n", "<M-r>", "<Cmd>FzfLua oldfiles<Cr>", { desc = "Old Files" })
vim.keymap.set("n", "<M-p>", "<Cmd>FzfLua global<Cr>", { desc = "Global" })
vim.keymap.set("n", "<leader>fa", "<Cmd>FzfLua<Cr>", { desc = "Fzf Lua Builtin" })
vim.keymap.set("n", "<leader>gf", "<Cmd>FzfLua git_files<Cr>", { desc = "Git Files" })
vim.keymap.set("n", "<leader>gc", "<Cmd>FzfLua git_commits<Cr>", { desc = "Git Commits" })

vim.keymap.set("n", "<leader>gP", function()
	Fzf.gh_pr({ state = "all" })
end, { desc = "GitHub Pull Requests (all)" })
-- Top Pickers & Explorer
vim.keymap.set("n", "<leader><space>", "<Cmd>FzfLua global<Cr>", { desc = "Smart Find Files" })
vim.keymap.set("n", "<M-h>", function()
	Fzf.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>,", function()
	Fzf.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>/", function()
	Fzf.live_grep()
end, { desc = "Grep" })
vim.keymap.set("n", "<leader>:", function()
	Fzf.command_history()
end, { desc = "Command History" })
vim.keymap.set("n", "<leader>n", function()
	Fzf.notifications()
end, { desc = "Notification History" })
vim.keymap.set("n", "<leader>e", function()
	Snacks.explorer()
end, { desc = "File Explorer" })
-- find
vim.keymap.set("n", "<leader>fb", function()
	Fzf.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>fc", function()
	Fzf.files({ cwd = vim.fn.stdpath("config") })
end, { desc = "Find Config File" })
vim.keymap.set("n", "<M-o>", function()
	Fzf.files()
end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>ff", function()
	Fzf.files()
end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>fg", function()
	Fzf.git_files()
end, { desc = "Find Git Files" })
vim.keymap.set("n", "<leader>fp", function()
	Fzf.projects()
end, { desc = "Projects" })
vim.keymap.set("n", "<leader>fo", function()
	Fzf.oldfiles()
end, { desc = "OldFiles" })
vim.keymap.set("n", "<leader>fr", function()
	Fzf.oldfiles()
end, { desc = "Recent" })
-- git
vim.keymap.set("n", "<leader>gb", function()
	Fzf.git_branches()
end, { desc = "Git Branches" })
vim.keymap.set("n", "<leader>gl", function()
	Fzf.git_log()
end, { desc = "Git Log" })
vim.keymap.set("n", "<leader>gL", function()
	Fzf.git_log_line()
end, { desc = "Git Log Line" })
vim.keymap.set("n", "<leader>gs", function()
	Fzf.git_status()
end, { desc = "Git Status" })
vim.keymap.set("n", "<leader>gS", function()
	Fzf.git_stash()
end, { desc = "Git Stash" })
vim.keymap.set("n", "<leader>gd", function()
	Fzf.git_diff()
end, { desc = "Git Diff (Hunks)" })
vim.keymap.set("n", "<leader>gf", function()
	Fzf.git_log_file()
end, { desc = "Git Log File" })
-- GitHub
vim.keymap.set("n", "<leader>gi", function()
	Fzf.gh_issue()
end, { desc = "GitHub Issues (open)" })
vim.keymap.set("n", "<leader>gI", function()
	Fzf.gh_issue({ state = "all" })
end, { desc = "GitHub Issues (all)" })
vim.keymap.set("n", "<leader>gp", function()
	Fzf.gh_pr()
end, { desc = "GitHub Pull Requests (open)" })
vim.keymap.set("n", "<leader>gP", function()
	Fzf.gh_pr({ state = "all" })
end, { desc = "GitHub Pull Requests (all)" })
-- Grep
vim.keymap.set("n", "<leader>sb", function()
	Fzf.lines()
end, { desc = "Buffer Lines" })
vim.keymap.set("n", "<leader>sB", function()
	Fzf.grep_buffers()
end, { desc = "Grep Open Buffers" })
vim.keymap.set("n", "<leader>sg", function()
	Fzf.grep()
end, { desc = "Grep" })
vim.keymap.set({ "n", "x" }, "<leader>sw", function()
	Fzf.grep_word()
end, { desc = "Visual selection or word" })
-- search
vim.keymap.set("n", '<leader>s"', function()
	Fzf.registers()
end, { desc = "Registers" })
vim.keymap.set("n", "<leader>s/", function()
	Fzf.search_history()
end, { desc = "Search History" })
vim.keymap.set("n", "<leader>sa", function()
	Fzf.autocmds()
end, { desc = "Autocmds" })
vim.keymap.set("n", "<leader>sb", function()
	Fzf.lines()
end, { desc = "Buffer Lines" })
vim.keymap.set("n", "<leader>sc", function()
	Fzf.command_history()
end, { desc = "Command History" })
vim.keymap.set("n", "<leader>sC", function()
	Fzf.commands()
end, { desc = "Commands" })
vim.keymap.set("n", "<leader>sd", function()
	Fzf.diagnostics()
end, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>sD", function()
	Fzf.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
vim.keymap.set("n", "<leader>sh", function()
	Fzf.help()
end, { desc = "Help Pages" })
vim.keymap.set("n", "<leader>sH", function()
	Fzf.highlights()
end, { desc = "Highlights" })
vim.keymap.set("n", "<leader>si", function()
	Fzf.icons()
end, { desc = "Icons" })
vim.keymap.set("n", "<leader>sj", function()
	Fzf.jumps()
end, { desc = "Jumps" })
vim.keymap.set("n", "<leader>sk", function()
	Fzf.keymaps()
end, { desc = "Keymaps" })
vim.keymap.set("n", "<leader>sl", function()
	Fzf.loclist()
end, { desc = "Location List" })
vim.keymap.set("n", "<leader>sm", function()
	Fzf.marks()
end, { desc = "Marks" })
vim.keymap.set("n", "<leader>sM", function()
	Fzf.man()
end, { desc = "Man Pages" })
vim.keymap.set("n", "<leader>sp", function()
	Fzf.lazy()
end, { desc = "Search for Plugin Spec" })
vim.keymap.set("n", "<leader>sq", function()
	Fzf.quickfix()
end, { desc = "Quickfix List" })
vim.keymap.set("n", "<leader>sR", function()
	Fzf.resume()
end, { desc = "Resume" })
vim.keymap.set("n", "<leader>su", function()
	Fzf.undotree()
end, { desc = "Undo History" })
vim.keymap.set("n", "<leader>uC", function()
	Fzf.colorschemes()
end, { desc = "Colorschemes" })
-- LSP
vim.keymap.set("n", "<leader>cd", function()
	Fzf.lsp_definitions()
end, { desc = "Goto Definition" })
vim.keymap.set("n", "<leader>cD", function()
	Fzf.lsp_declarations()
end, { desc = "Goto Declaration" })
vim.keymap.set("n", "<leader>cr", function()
	Fzf.lsp_references()
end, { nowait = true, desc = "References" })
vim.keymap.set("n", "<leader>cI", function()
	Fzf.lsp_implementations()
end, { desc = "Goto Implementation" })
vim.keymap.set("n", "<leader>cy", function()
	Fzf.lsp_type_definitions()
end, { desc = "Goto T[y]pe Definition" })
vim.keymap.set("n", "<leader>ci", function()
	Fzf.lsp_incoming_calls()
end, { desc = "C[a]lls Incoming" })
vim.keymap.set("n", "<leader>co", function()
	Fzf.lsp_outgoing_calls()
end, { desc = "C[a]lls Outgoing" })
vim.keymap.set("n", "<leader>ss", function()
	Fzf.lsp_symbols()
end, { desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>sS", function()
	Fzf.lsp_workspace_symbols()
end, { desc = "LSP Workspace Symbols" })
end)
