-- vim.schedule(function()
--   vim.cmd.packadd("mason.nvim")
--   vim.cmd.packadd("mason-lspconfig.nvim")
--   vim.cmd.packadd("nvim-lspconfig")
--   require("mason").setup()
--   require("mason-lspconfig").setup({
--     automatic_enable = true,
--   })
-- end)
