-- -- REF: https://www.reddit.com/r/NixOS/comments/1raqini/i_built_a_vs_code_extension_that_brings_syntax/
-- vim.schedule(function()
--   vim.cmd.packadd("nvim-treesitter")
-- 	vim.cmd.packadd("tree-sitter-manager.nvim")
--
-- 	-- build = ":TSUpdate",
-- 	local ts = require("nvim-treesitter")
-- 	ts.setup({
-- 		install_dir = vim.fn.stdpath("data") .. "/site",
-- 	})
-- 	ts.install("all", { summary = false }, { max_jobs = 24 }):wait(1000000)
--
-- 	vim.api.nvim_create_autocmd("FileType", {
-- 		pattern = "*",
-- 		callback = function()
-- 			if pcall(vim.treesitter.start) then
-- 				-- Indent expérimental
-- 				-- vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
-- 				-- Folds
-- 				vim.wo[0][0].foldmethod = "expr"
-- 				vim.wo[0][0].foldexpr = "v:lua.vim.treesitter.foldexpr()"
-- 			end
-- 		end,
-- 	})
--
-- 	-- {
-- 	-- 	"nvim-treesitter/nvim-treesitter-textobjects",
-- 	-- 	branch = "main",
-- 	-- 	lazy = true,
-- 	-- 	event = "VeryLazy",
-- 	-- },
--
-- 	vim.cmd.packadd("tree-sitter-manager.nvim")
--
-- 	require("tree-sitter-manager").setup({
-- 		-- Optional: custom paths
-- 		-- parser_dir = vim.fn.stdpath("data") .. "/site/parser",
-- 		-- query_dir = vim.fn.stdpath("data") .. "/site/queries",
-- 	})
-- end)
