----------------------
-- VS CODE CONFIG  ---
----------------------
if vim.g.vscode then
  vim.o.showmode = true
  vim.keymap.set("n", "<leader><space>", function()
    require("vscode").call("workbench.action.quickOpen")
  end)
  vim.keymap.set("n", "<leader>,", function()
    require("vscode").call("workbench.action.showAllEditors")
  end)
  vim.keymap.set("n", "<leader>e", function()
    require("vscode").call("workbench.view.explorer")
  end)
  vim.keymap.set("n", "<leader><Cr>", function()
    require("vscode").call("oil-code.open")
  end)
  vim.keymap.set("n", "<leader>tn", function()
    require("vscode").call("workbench.action.createTerminalEditor")
  end)
  vim.keymap.set("n", "<leader>/", function()
    require("vscode").call("workbench.action.quickTextSearch")
  end)
  -- vim.keymap.set("n", "<leader>gg", function()
  --   require("vscode").call("lazygit.openLazygit")
  -- end)
  -- vim.keymap.set("n", "<leader>G", function()
  --   require("vscode").call("fugitive.open")
  -- end)
  vim.keymap.set("n", "<leader>gg", function()
    require("vscode").call("magit.status")
  end)
  vim.keymap.set("n", "gd", function()
    require("vscode").call("editor.action.revealDefinition")
  end)
  vim.keymap.set("n", "gr", function()
    require("vscode").call("editor.action.goToReferences")
  end)
  vim.keymap.set("n", "j", "gj")
  vim.keymap.set("n", "k", "gk")
  vim.keymap.set("n", "<leader>ha", function()
    require("vscode").call("vscode-harpoon.addEditor")
  end)
  vim.keymap.set("n", "<leader>he", function()
    require("vscode").call("vscode-harpoon.editEditors")
  end)
  for i = 1, 9 do
    vim.keymap.set("n", "<leader>" .. i, function()
      require("vscode").call("vscode-harpoon.gotoEditor" .. i)
    end)
    vim.keymap.set("n", "<leader>h" .. i, function()
      require("vscode").call("vscode-harpoon.addGlobalEditor" .. i)
    end)
  end
  -- config from https://www.reddit.com/r/neovim/comments/1kspket/comment/mtslipm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
  vim.keymap.set("n", "<leader>cf", function()
    require("vscode").call("editor.action.formatDocument")
  end)
  vim.keymap.set("n", "<leader>bo", function()
    require("vscode").call("workbench.action.closeOtherEditors")
  end)
  vim.keymap.set("n", "<leader>ca", function()
    require("vscode").call("editor.action.quickFix")
  end, {})
  vim.keymap.set("n", "<leader>cr", function()
    require("vscode").call("editor.action.rename")
  end, {})
  vim.keymap.set("n", "K", function()
    require("vscode").call("editor.action.showHover")
  end)
  vim.keymap.set("n", "<leader>wq", function()
    require("vscode").call("workbench.action.closeActiveEditor")
  end, {})
  vim.keymap.set("n", "gd", function()
    require("vscode").call("editor.action.revealDefinition")
  end, {})
  vim.keymap.set("n", "gr", function()
    require("vscode").call("editor.action.goToReferences")
  end, {})
  vim.keymap.set("n", "gi", function()
    require("vscode").call("editor.action.goToImplementation")
  end, {})
  vim.keymap.set("n", "zM", function()
    require("vscode").call("editor.foldAll")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "zR", function()
    require("vscode").call("editor.unfoldAll")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "zc", function()
    require("vscode").call("editor.fold")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "zC", function()
    require("vscode").call("editor.foldRecursively")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "zo", function()
    require("vscode").call("editor.unfold")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "zO", function()
    require("vscode").call("editor.unfoldRecursively")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "za", function()
    require("vscode").call("editor.toggleFold")
  end, { noremap = true, silent = true })
  vim.keymap.set("n", "<leader>qr", function()
    require("vscode").call("workbench.action.reloadWindow")
  end, { noremap = true, silent = true })

end
