-- colors/tokyo.lua
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

local N = "NONE"

---@param groups table<string, table>  { Group = { fg=, bg=, sp=, bold=, ... } }
---@param links table<string, string>  { Group = "TargetGroup" }
local function apply(groups, links)
  for name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, name, spec)
  end
  for name, target in pairs(links) do
    vim.api.nvim_set_hl(0, name, { link = target })
  end
end

if vim.o.background == "dark" then
  vim.g.colors_name = "tokyo"

  apply({
    ALEErrorSign = { bg = N, fg = "#db4b4b" },
    ALEWarningSign = { bg = N, fg = "#e0af68" },
    Bold = { bold = true, bg = N, fg = "#c0caf5" },
    Character = { bg = N, fg = "#9ece6a" },
    ColorColumn = { bg = "#15161e" },
    Comment = { italic = true, bg = N, fg = "#565f89" },
    ComplHint = { bg = N, fg = "#414868" },
    Conceal = { bg = N, fg = "#737aa2" },
    Constant = { bg = N, fg = "#ff9e64" },
    CopilotAnnotation = { bg = N, fg = "#414868" },
    CopilotSuggestion = { bg = N, fg = "#414868" },
    Cursor = { bg = "#c0caf5", fg = "#1a1b26" },
    CursorColumn = { bg = "#292e42" },
    CursorIM = { bg = "#c0caf5", fg = "#1a1b26" },
    CursorLine = { bg = "#292e42" },
    CursorLineNr = { bold = true, bg = N, fg = "#ff9e64" },
    Debug = { bg = N, fg = "#ff9e64" },
    DiagnosticError = { bg = N, fg = "#db4b4b" },
    DiagnosticHint = { bg = N, fg = "#1abc9c" },
    DiagnosticInfo = { bg = N, fg = "#0db9d7" },
    DiagnosticUnderlineError = { undercurl = true, bg = N, sp = "#db4b4b" },
    DiagnosticUnderlineHint = { undercurl = true, bg = N, sp = "#1abc9c" },
    DiagnosticUnderlineInfo = { undercurl = true, bg = N, sp = "#0db9d7" },
    DiagnosticUnderlineWarn = { undercurl = true, bg = N, sp = "#e0af68" },
    DiagnosticUnnecessary = { bg = N, fg = "#414868" },
    DiagnosticVirtualTextError = { bg = "#2d202a", fg = "#db4b4b" },
    DiagnosticVirtualTextHint = { bg = "#1a2b32", fg = "#1abc9c" },
    DiagnosticVirtualTextInfo = { bg = "#192b38", fg = "#0db9d7" },
    DiagnosticVirtualTextWarn = { bg = "#2e2a2d", fg = "#e0af68" },
    DiagnosticWarn = { bg = N, fg = "#e0af68" },
    DiffAdd = { bg = "#243e4a" },
    DiffChange = { bg = "#1f2231" },
    DiffDelete = { bg = "#4a272f" },
    DiffText = { bg = "#394b70" },
    Directory = { bg = N, fg = "#7aa2f7" },
    EndOfBuffer = { bg = N, fg = "#1a1b26" },
    Error = { bg = N, fg = "#db4b4b" },
    ErrorMsg = { bg = N, fg = "#db4b4b" },
    FloatBorder = { bg = "#16161e", fg = "#27a1b9" },
    FloatTitle = { bg = "#16161e", fg = "#27a1b9" },
    FoldColumn = { bg = "#1a1b26", fg = "#565f89" },
    Folded = { bg = "#3b4261", fg = "#7aa2f7" },
    Foo = { bg = "#ff007c", fg = "#c0caf5" },
    Function = { bg = N, fg = "#7aa2f7" },
    GitGutterAdd = { bg = N, fg = "#449dab" },
    GitGutterAddLineNr = { bg = N, fg = "#449dab" },
    GitGutterChange = { bg = N, fg = "#6183bb" },
    GitGutterChangeLineNr = { bg = N, fg = "#6183bb" },
    GitGutterDelete = { bg = N, fg = "#914c54" },
    GitGutterDeleteLineNr = { bg = N, fg = "#914c54" },
    GlyphPalette1 = { bg = N, fg = "#db4b4b" },
    GlyphPalette2 = { bg = N, fg = "#9ece6a" },
    GlyphPalette3 = { bg = N, fg = "#e0af68" },
    GlyphPalette4 = { bg = N, fg = "#7aa2f7" },
    GlyphPalette6 = { bg = N, fg = "#73daca" },
    GlyphPalette7 = { bg = N, fg = "#c0caf5" },
    GlyphPalette9 = { bg = N, fg = "#f7768e" },
    Identifier = { bg = N, fg = "#bb9af7" },
    IlluminatedWordRead = { bg = "#3b4261" },
    IlluminatedWordText = { bg = "#3b4261" },
    IlluminatedWordWrite = { bg = "#3b4261" },
    IncSearch = { bg = "#ff9e64", fg = "#15161e" },
    Italic = { italic = true, bg = N, fg = "#c0caf5" },
    Keyword = { italic = true, bg = N, fg = "#7dcfff" },
    LineNr = { bg = N, fg = "#3b4261" },
    LineNrAbove = { bg = N, fg = "#3b4261" },
    LineNrBelow = { bg = N, fg = "#3b4261" },
    LspCodeLens = { bg = N, fg = "#565f89" },
    LspInfoBorder = { bg = "#16161e", fg = "#27a1b9" },
    LspInlayHint = { bg = "#1d202d", fg = "#545c7e" },
    LspReferenceRead = { bg = "#3b4261" },
    LspReferenceText = { bg = "#3b4261" },
    LspReferenceWrite = { bg = "#3b4261" },
    LspSignatureActiveParameter = { bold = true, bg = "#20253a" },
    MatchParen = { bold = true, bg = N, fg = "#ff9e64" },
    ModeMsg = { bold = true, bg = N, fg = "#a9b1d6" },
    MoreMsg = { bg = N, fg = "#7aa2f7" },
    MsgArea = { bg = N, fg = "#a9b1d6" },
    Variable = { bg = N, fg = "#bb9af7" },
    Indentifier = { bg = N, fg = "#bb9af7" }, -- typo in the original ("Indentifier"), harmless
    NonText = { bg = N, fg = "#545c7e" },
    Normal = { bg = "#1a1b26", fg = "#c0caf5" },
    NormalFloat = { bg = "#16161e", fg = "#c0caf5" },
    NormalNC = { bg = "#1a1b26", fg = "#c0caf5" },
    NormalSB = { bg = "#16161e", fg = "#a9b1d6" },
    Operator = { bg = N, fg = "#89ddff" },
    Pmenu = { bg = "#16161e", fg = "#c0caf5" },
    PmenuMatch = { bg = "#16161e", fg = "#2ac3de" },
    PmenuMatchSel = { bg = "#343a55", fg = "#2ac3de" },
    PmenuSbar = { bg = "#1f1f29" },
    PmenuSel = { bg = "#343a55" },
    PmenuThumb = { bg = "#3b4261" },
    PreProc = { bg = N, fg = "#7dcfff" },
    Question = { bg = N, fg = "#7aa2f7" },
    QuickFixLine = { bold = true, bg = "#283457" },
    Search = { bg = "#3d59a1", fg = "#c0caf5" },
    SignColumn = { bg = "#1a1b26", fg = "#3b4261" },
    SignColumnSB = { bg = "#16161e", fg = "#3b4261" },
    Sneak = { bg = "#bb9af7", fg = "#292e42" },
    SneakScope = { bg = "#283457" },
    Special = { bg = N, fg = "#2ac3de" },
    SpecialKey = { bg = N, fg = "#545c7e" },
    SpellBad = { undercurl = true, bg = N, sp = "#db4b4b" },
    SpellCap = { undercurl = true, bg = N, sp = "#e0af68" },
    SpellLocal = { undercurl = true, bg = N, sp = "#0db9d7" },
    SpellRare = { undercurl = true, bg = N, sp = "#1abc9c" },
    Statement = { bg = N, fg = "#bb9af7" },
    String = { bg = N, fg = "#9ece6a" },
    Substitute = { bg = "#f7768e", fg = "#15161e" },
    TabLineSel = { bg = "#7aa2f7", fg = "#15161e" },
    Title = { bold = true, bg = N, fg = "#7aa2f7" },
    Todo = { bg = "#e0af68", fg = "#1a1b26" },
    Type = { bg = N, fg = "#2ac3de" },
    Underlined = { underline = true, bg = N },
    VertSplit = { bg = N, fg = "#15161e" },
    VimwikiHR = { bg = N, fg = "#e0af68" },
    VimwikiHeader1 = { bold = true, bg = N, fg = "#7aa2f7" },
    VimwikiHeader2 = { bold = true, bg = N, fg = "#e0af68" },
    VimwikiHeader3 = { bold = true, bg = N, fg = "#9ece6a" },
    VimwikiHeader4 = { bold = true, bg = N, fg = "#1abc9c" },
    VimwikiHeader5 = { bold = true, bg = N, fg = "#bb9af7" },
    VimwikiHeader6 = { bold = true, bg = N, fg = "#9d7cd8" },
    VimwikiHeader7 = { bold = true, bg = N, fg = "#ff9e64" },
    VimwikiHeader8 = { bold = true, bg = N, fg = "#f7768e" },
    VimwikiHeaderChar = { bg = N, fg = "#e0af68" },
    VimwikiLink = { bg = N, fg = "#7aa2f7" },
    VimwikiList = { bg = N, fg = "#ff9e64" },
    VimwikiMarkers = { bg = N, fg = "#7aa2f7" },
    VimwikiTag = { bg = N, fg = "#9ece6a" },
    Visual = { bg = "#283457" },
    VisualNOS = { bg = "#283457" },
    WarningMsg = { bg = N, fg = "#e0af68" },
    Whitespace = { bg = N, fg = "#3b4261" },
    WildMenu = { bg = "#283457" },
    WinSeparator = { bold = true, bg = N, fg = "#15161e" },
    debugBreakpoint = { bg = "#192b38", fg = "#0db9d7" },
    debugPC = { bg = "#16161e" },
    diffAdded = { bg = "#243e4a", fg = "#449dab" },
    diffChanged = { bg = "#1f2231", fg = "#6183bb" },
    diffFile = { bg = N, fg = "#7aa2f7" },
    diffIndexLine = { bg = N, fg = "#bb9af7" },
    diffLine = { bg = N, fg = "#565f89" },
    diffNewFile = { bg = "#243e4a", fg = "#2ac3de" },
    diffOldFile = { bg = "#4a272f", fg = "#2ac3de" },
    diffRemoved = { bg = "#4a272f", fg = "#914c54" },
    healthError = { bg = N, fg = "#db4b4b" },
    healthSuccess = { bg = N, fg = "#73daca" },
    healthWarning = { bg = N, fg = "#e0af68" },
    helpCommand = { bg = "#414868", fg = "#7aa2f7" },
    helpExample = { bg = N, fg = "#565f89" },
    htmlH1 = { bold = true, bg = N, fg = "#bb9af7" },
    htmlH2 = { bold = true, bg = N, fg = "#7aa2f7" },
    illuminatedCurWord = { bg = "#3b4261" },
    illuminatedWord = { bg = "#3b4261" },
    lCursor = { bg = "#c0caf5", fg = "#1a1b26" },
    qfFileName = { bg = N, fg = "#7aa2f7" },
    qfLineNr = { bg = N, fg = "#737aa2" },
  }, {
    StatusLine = "Normal",
    StatusLineNC = "NormalNC",
    TabLine = "Normal",
    TabLineFill = "Normal",
    CurSearch = "IncSearch",
    Delimiter = "Special",
    LspKindColor = "Special",
    LspKindEvent = "Special",
    LspKindFile = "Normal",
    LspKindFolder = "Directory",
    LspKindSnippet = "Conceal",
    WinBarNC = "StatusLineNC",
  })
else
  vim.g.colors_name = "tokyo-day"

  apply({
    ALEErrorSign = { bg = N, fg = "#c64343" },
    ALEWarningSign = { bg = N, fg = "#8c6c3e" },
    BlinkCmpDoc = { bg = "#d0d5e3", fg = "#3760bf" },
    BlinkCmpDocBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    BlinkCmpGhostText = { bg = N, fg = "#a1a6c5" },
    BlinkCmpKindCodeium = { bg = N, fg = "#118c74" },
    BlinkCmpKindCopilot = { bg = N, fg = "#118c74" },
    BlinkCmpKindDefault = { bg = N, fg = "#6172b0" },
    BlinkCmpKindSupermaven = { bg = N, fg = "#118c74" },
    BlinkCmpKindTabNine = { bg = N, fg = "#118c74" },
    BlinkCmpLabel = { bg = N, fg = "#3760bf" },
    BlinkCmpLabelDeprecated = { strikethrough = true, bg = N, fg = "#a8aecb" },
    BlinkCmpLabelMatch = { bg = N, fg = "#188092" },
    BlinkCmpMenu = { bg = "#d0d5e3", fg = "#3760bf" },
    BlinkCmpMenuBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    BlinkCmpSignatureHelp = { bg = "#d0d5e3", fg = "#3760bf" },
    BlinkCmpSignatureHelpBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    Bold = { bold = true, bg = N, fg = "#3760bf" },
    Character = { bg = N, fg = "#587539" },
    ColorColumn = { bg = "#b4b5b9" },
    Comment = { italic = true, bg = N, fg = "#848cb5" },
    ComplHint = { bg = N, fg = "#a1a6c5" },
    Conceal = { bg = N, fg = "#68709a" },
    Constant = { bg = N, fg = "#b15c00" },
    CopilotAnnotation = { bg = N, fg = "#a1a6c5" },
    CopilotSuggestion = { bg = N, fg = "#a1a6c5" },
    Cursor = { bg = "#3760bf", fg = "#e1e2e7" },
    CursorColumn = { bg = "#c4c8da" },
    CursorIM = { bg = "#3760bf", fg = "#e1e2e7" },
    CursorLine = { bg = "#c4c8da" },
    CursorLineNr = { bold = true, bg = N, fg = "#b15c00" },
    Debug = { bg = N, fg = "#b15c00" },
    DiagnosticError = { bg = N, fg = "#c64343" },
    DiagnosticHint = { bg = N, fg = "#118c74" },
    DiagnosticInfo = { bg = N, fg = "#07879d" },
    DiagnosticUnderlineError = { undercurl = true, bg = N, sp = "#c64343" },
    DiagnosticUnderlineHint = { undercurl = true, bg = N, sp = "#118c74" },
    DiagnosticUnderlineInfo = { undercurl = true, bg = N, sp = "#07879d" },
    DiagnosticUnderlineWarn = { undercurl = true, bg = N, sp = "#8c6c3e" },
    DiagnosticUnnecessary = { bg = N, fg = "#a1a6c5" },
    DiagnosticVirtualTextError = { bg = "#ded2d7", fg = "#c64343" },
    DiagnosticVirtualTextHint = { bg = "#ccd9dc", fg = "#118c74" },
    DiagnosticVirtualTextInfo = { bg = "#cbd9e0", fg = "#07879d" },
    DiagnosticVirtualTextWarn = { bg = "#d9d6d6", fg = "#8c6c3e" },
    DiagnosticWarn = { bg = N, fg = "#8c6c3e" },
    DiffAdd = { bg = "#b7ced5" },
    DiffChange = { bg = "#d5d9e4" },
    DiffDelete = { bg = "#dababe" },
    DiffText = { bg = "#92a6d5" },
    Directory = { bg = N, fg = "#2e7de9" },
    EndOfBuffer = { bg = N, fg = "#e1e2e7" },
    Error = { bg = N, fg = "#c64343" },
    ErrorMsg = { bg = N, fg = "#c64343" },
    FloatBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    FloatTitle = { bg = "#d0d5e3", fg = "#4094a3" },
    FoldColumn = { bg = "#e1e2e7", fg = "#848cb5" },
    Folded = { bg = "#a8aecb", fg = "#2e7de9" },
    Foo = { bg = "#d20065", fg = "#3760bf" },
    Function = { bg = N, fg = "#2e7de9" },
    FzfLuaBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    FzfLuaDirPart = { bg = N, fg = "#6172b0" },
    FzfLuaFzfNormal = { bg = N, fg = "#3760bf" },
    FzfLuaFzfPointer = { bg = N, fg = "#d20065" },
    FzfLuaFzfSeparator = { bg = "#d0d5e3", fg = "#b15c00" },
    FzfLuaNormal = { bg = "#d0d5e3", fg = "#3760bf" },
    FzfLuaPreviewTitle = { bg = "#d0d5e3", fg = "#4094a3" },
    FzfLuaTitle = { bg = "#d0d5e3", fg = "#b15c00" },
    GitGutterAdd = { bg = N, fg = "#4197a4" },
    GitGutterAddLineNr = { bg = N, fg = "#4197a4" },
    GitGutterChange = { bg = N, fg = "#506d9c" },
    GitGutterChangeLineNr = { bg = N, fg = "#506d9c" },
    GitGutterDelete = { bg = N, fg = "#c47981" },
    GitGutterDeleteLineNr = { bg = N, fg = "#c47981" },
    GlyphPalette1 = { bg = N, fg = "#c64343" },
    GlyphPalette2 = { bg = N, fg = "#587539" },
    GlyphPalette3 = { bg = N, fg = "#8c6c3e" },
    GlyphPalette4 = { bg = N, fg = "#2e7de9" },
    GlyphPalette6 = { bg = N, fg = "#387068" },
    GlyphPalette7 = { bg = N, fg = "#3760bf" },
    GlyphPalette9 = { bg = N, fg = "#f52a65" },
    Identifier = { bg = N, fg = "#9854f1" },
    IlluminatedWordRead = { bg = "#a8aecb" },
    IlluminatedWordText = { bg = "#a8aecb" },
    IlluminatedWordWrite = { bg = "#a8aecb" },
    IncSearch = { bg = "#b15c00", fg = "#b4b5b9" },
    Italic = { italic = true, bg = N, fg = "#3760bf" },
    Keyword = { italic = true, bg = N, fg = "#007197" },
    LineNr = { bg = N, fg = "#a8aecb" },
    LineNrAbove = { bg = N, fg = "#a8aecb" },
    LineNrBelow = { bg = N, fg = "#a8aecb" },
    LspCodeLens = { bg = N, fg = "#848cb5" },
    LspInfoBorder = { bg = "#d0d5e3", fg = "#4094a3" },
    LspInlayHint = { bg = "#d9dce5", fg = "#8990b3" },
    LspReferenceRead = { bg = "#a8aecb" },
    LspReferenceText = { bg = "#a8aecb" },
    LspReferenceWrite = { bg = "#a8aecb" },
    LspSignatureActiveParameter = { bold = true, bg = "#d0d5e5" },
    MatchParen = { bold = true, bg = N, fg = "#b15c00" },
    MiniAnimateCursor = { nocombine = true, bg = N },
    MiniCompletionActiveParameter = { underline = true, bg = N },
    MiniCursorword = { bg = "#a8aecb" },
    MiniCursorwordCurrent = { bg = "#a8aecb" },
    MiniDepsTitleError = { bg = "#c47981", fg = "#b4b5b9" },
    MiniDepsTitleUpdate = { bg = "#4197a4", fg = "#b4b5b9" },
    MiniDiffSignAdd = { bg = N, fg = "#4197a4" },
    MiniDiffSignChange = { bg = N, fg = "#506d9c" },
    MiniDiffSignDelete = { bg = N, fg = "#c47981" },
    MiniFilesFile = { bg = N, fg = "#3760bf" },
    MiniFilesTitleFocused = { bold = true, bg = "#d0d5e3", fg = "#4094a3" },
    MiniHipatternsFixme = { bold = true, bg = "#c64343", fg = "#b4b5b9" },
    MiniHipatternsHack = { bold = true, bg = "#8c6c3e", fg = "#b4b5b9" },
    MiniHipatternsNote = { bold = true, bg = "#118c74", fg = "#b4b5b9" },
    MiniHipatternsTodo = { bold = true, bg = "#07879d", fg = "#b4b5b9" },
    MiniIconsAzure = { bg = N, fg = "#07879d" },
    MiniIconsBlue = { bg = N, fg = "#2e7de9" },
    MiniIconsCyan = { bg = N, fg = "#118c74" },
    MiniIconsGreen = { bg = N, fg = "#587539" },
    MiniIconsGrey = { bg = N, fg = "#3760bf" },
    MiniIconsOrange = { bg = N, fg = "#b15c00" },
    MiniIconsPurple = { bg = N, fg = "#7847bd" },
    MiniIconsRed = { bg = N, fg = "#f52a65" },
    MiniIconsYellow = { bg = N, fg = "#8c6c3e" },
    MiniIndentscopePrefix = { nocombine = true, bg = N },
    MiniIndentscopeSymbol = { nocombine = true, bg = N, fg = "#188092" },
    MiniJump = { bg = "#d20065", fg = "#ffffff" },
    MiniJump2dSpot = { bold = true, nocombine = true, bg = N, fg = "#d20065" },
    MiniJump2dSpotAhead = { nocombine = true, bg = "#d0d5e3", fg = "#118c74" },
    MiniJump2dSpotUnique = { bold = true, nocombine = true, bg = N, fg = "#b15c00" },
    MiniPickBorderText = { bg = "#d0d5e3", fg = "#118c74" },
    MiniPickPrompt = { bg = "#d0d5e3", fg = "#07879d" },
    MiniStarterCurrent = { nocombine = true, bg = N },
    MiniStarterFooter = { italic = true, bg = N, fg = "#8c6c3e" },
    MiniStarterHeader = { bg = N, fg = "#2e7de9" },
    MiniStarterInactive = { italic = true, bg = N, fg = "#848cb5" },
    MiniStarterItem = { bg = "#e1e2e7", fg = "#3760bf" },
    MiniStarterItemBullet = { bg = N, fg = "#4094a3" },
    MiniStarterItemPrefix = { bg = N, fg = "#8c6c3e" },
    MiniStarterQuery = { bg = N, fg = "#07879d" },
    MiniStarterSection = { bg = N, fg = "#188092" },
    MiniStatuslineDevinfo = { bg = "#a8aecb", fg = "#6172b0" },
    MiniStatuslineFileinfo = { bg = "#a8aecb", fg = "#6172b0" },
    MiniStatuslineFilename = { bg = "#c4c8da", fg = "#6172b0" },
    MiniStatuslineInactive = { bg = "#d0d5e3", fg = "#2e7de9" },
    MiniStatuslineModeCommand = { bold = true, bg = "#8c6c3e", fg = "#b4b5b9" },
    MiniStatuslineModeInsert = { bold = true, bg = "#587539", fg = "#b4b5b9" },
    MiniStatuslineModeNormal = { bold = true, bg = "#2e7de9", fg = "#b4b5b9" },
    MiniStatuslineModeOther = { bold = true, bg = "#118c74", fg = "#b4b5b9" },
    MiniStatuslineModeReplace = { bold = true, bg = "#f52a65", fg = "#b4b5b9" },
    MiniStatuslineModeVisual = { bold = true, bg = "#9854f1", fg = "#b4b5b9" },
    MiniSurround = { bg = "#b15c00", fg = "#b4b5b9" },
    MiniTablineCurrent = { bg = "#a8aecb", fg = "#3760bf" },
    MiniTablineFill = { bg = "#b4b5b9" },
    MiniTablineHidden = { bg = "#d0d5e3", fg = "#68709a" },
    MiniTablineModifiedCurrent = { bg = "#a8aecb", fg = "#8c6c3e" },
    MiniTablineModifiedHidden = { bg = "#d0d5e3", fg = "#a68f71" },
    MiniTablineModifiedVisible = { bg = "#d0d5e3", fg = "#8c6c3e" },
    MiniTablineTabpagesection = { bg = "#a8aecb", fg = N },
    MiniTablineVisible = { bg = "#d0d5e3", fg = "#3760bf" },
    MiniTestEmphasis = { bold = true, bg = N },
    MiniTestFail = { bold = true, bg = N, fg = "#f52a65" },
    MiniTestPass = { bold = true, bg = N, fg = "#587539" },
    MiniTrailspace = { bg = "#f52a65" },
    ModeMsg = { bold = true, bg = N, fg = "#6172b0" },
    MoreMsg = { bg = N, fg = "#2e7de9" },
    MsgArea = { bg = N, fg = "#6172b0" },
    NeogitBranch = { bg = N, fg = "#9854f1" },
    NeogitDiffAddHighlight = { bg = "#b7ced5", fg = "#4197a4" },
    NeogitDiffContextHighlight = { bg = "#c5c8d9", fg = "#6172b0" },
    NeogitDiffDeleteHighlight = { bg = "#dababe", fg = "#c47981" },
    NeogitHunkHeader = { bg = "#c4c8da", fg = "#3760bf" },
    NeogitHunkHeaderHighlight = { bg = "#a8aecb", fg = "#2e7de9" },
    NeogitRemote = { bg = N, fg = "#7847bd" },
    NeotestAdapterName = { bold = true, bg = N, fg = "#7847bd" },
    NeotestBorder = { bg = N, fg = "#2e7de9" },
    NeotestDir = { bg = N, fg = "#2e7de9" },
    NeotestExpandMarker = { bg = N, fg = "#6172b0" },
    NeotestFailed = { bg = N, fg = "#f52a65" },
    NeotestFile = { bg = N, fg = "#118c74" },
    NeotestFocused = { bg = N, fg = "#8c6c3e" },
    NeotestIndent = { bg = N, fg = "#6172b0" },
    NeotestMarked = { bg = N, fg = "#2e7de9" },
    NeotestNamespace = { bg = N, fg = "#38919f" },
    NeotestPassed = { bg = N, fg = "#587539" },
    NeotestRunning = { bg = N, fg = "#8c6c3e" },
    NeotestSkipped = { bg = N, fg = "#2e7de9" },
    NeotestTarget = { bg = N, fg = "#2e7de9" },
    NeotestTest = { bg = N, fg = "#6172b0" },
    NeotestWinSelect = { bg = N, fg = "#2e7de9" },
    NonText = { bg = N, fg = "#8990b3" },
    Normal = { bg = "#e1e2e7", fg = "#3760bf" },
    NormalFloat = { bg = "#d0d5e3", fg = "#3760bf" },
    NormalNC = { bg = "#e1e2e7", fg = "#3760bf" },
    NormalSB = { bg = "#d0d5e3", fg = "#6172b0" },
    Operator = { bg = N, fg = "#006a83" },
    Pmenu = { bg = "#d0d5e3", fg = "#3760bf" },
    PmenuMatch = { bg = "#d0d5e3", fg = "#188092" },
    PmenuMatchSel = { bg = "#b3b8d1", fg = "#188092" },
    PmenuSbar = { bg = "#c8cfe1" },
    PmenuSel = { bg = "#b3b8d1" },
    PmenuThumb = { bg = "#a8aecb" },
    PreProc = { bg = N, fg = "#007197" },
    Question = { bg = N, fg = "#2e7de9" },
    QuickFixLine = { bold = true, bg = "#b7c1e3" },
    Search = { bg = "#7890dd", fg = "#3760bf" },
    SignColumn = { bg = "#e1e2e7", fg = "#a8aecb" },
    SignColumnSB = { bg = "#d0d5e3", fg = "#a8aecb" },
    Sneak = { bg = "#9854f1", fg = "#c4c8da" },
    SneakScope = { bg = "#b7c1e3" },
    Special = { bg = N, fg = "#188092" },
    SpecialKey = { bg = N, fg = "#8990b3" },
    SpellBad = { undercurl = true, bg = N, sp = "#c64343" },
    SpellCap = { undercurl = true, bg = N, sp = "#8c6c3e" },
    SpellLocal = { undercurl = true, bg = N, sp = "#07879d" },
    SpellRare = { undercurl = true, bg = N, sp = "#118c74" },
    Statement = { bg = N, fg = "#9854f1" },
    StatusLine = { bg = "#d0d5e3", fg = "#6172b0" },
    StatusLineNC = { bg = "#d0d5e3", fg = "#a8aecb" },
    String = { bg = N, fg = "#587539" },
    Substitute = { bg = "#f52a65", fg = "#b4b5b9" },
    TabLine = { bg = "#d0d5e3", fg = "#a8aecb" },
    TabLineFill = { bg = "#b4b5b9" },
    TabLineSel = { bg = "#2e7de9", fg = "#b4b5b9" },
    Title = { bold = true, bg = N, fg = "#2e7de9" },
    Todo = { bg = "#8c6c3e", fg = "#e1e2e7" },
    Type = { bg = N, fg = "#188092" },
    Underlined = { underline = true, bg = N },
    VertSplit = { bg = N, fg = "#b4b5b9" },
    VimwikiHR = { bg = N, fg = "#8c6c3e" },
    VimwikiHeader1 = { bold = true, bg = N, fg = "#2e7de9" },
    VimwikiHeader2 = { bold = true, bg = N, fg = "#8c6c3e" },
    VimwikiHeader3 = { bold = true, bg = N, fg = "#587539" },
    VimwikiHeader4 = { bold = true, bg = N, fg = "#118c74" },
    VimwikiHeader5 = { bold = true, bg = N, fg = "#9854f1" },
    VimwikiHeader6 = { bold = true, bg = N, fg = "#7847bd" },
    VimwikiHeader7 = { bold = true, bg = N, fg = "#b15c00" },
    VimwikiHeader8 = { bold = true, bg = N, fg = "#f52a65" },
    VimwikiHeaderChar = { bg = N, fg = "#8c6c3e" },
    VimwikiLink = { bg = N, fg = "#2e7de9" },
    VimwikiList = { bg = N, fg = "#b15c00" },
    VimwikiMarkers = { bg = N, fg = "#2e7de9" },
    VimwikiTag = { bg = N, fg = "#587539" },
    Visual = { bg = "#b7c1e3" },
    VisualNOS = { bg = "#b7c1e3" },
    WarningMsg = { bg = N, fg = "#8c6c3e" },
    Whitespace = { bg = N, fg = "#a8aecb" },
    WildMenu = { bg = "#b7c1e3" },
    WinSeparator = { bold = true, bg = N, fg = "#b4b5b9" },
    debugBreakpoint = { bg = "#cbd9e0", fg = "#07879d" },
    debugPC = { bg = "#d0d5e3" },
    diffAdded = { bg = "#b7ced5", fg = "#4197a4" },
    diffChanged = { bg = "#d5d9e4", fg = "#506d9c" },
    diffFile = { bg = N, fg = "#2e7de9" },
    diffIndexLine = { bg = N, fg = "#9854f1" },
    diffLine = { bg = N, fg = "#848cb5" },
    diffNewFile = { bg = "#b7ced5", fg = "#188092" },
    diffOldFile = { bg = "#dababe", fg = "#188092" },
    diffRemoved = { bg = "#dababe", fg = "#c47981" },
    healthError = { bg = N, fg = "#c64343" },
    healthSuccess = { bg = N, fg = "#387068" },
    healthWarning = { bg = N, fg = "#8c6c3e" },
    helpCommand = { bg = "#a1a6c5", fg = "#2e7de9" },
    helpExample = { bg = N, fg = "#848cb5" },
    htmlH1 = { bold = true, bg = N, fg = "#9854f1" },
    htmlH2 = { bold = true, bg = N, fg = "#2e7de9" },
    illuminatedCurWord = { bg = "#a8aecb" },
    illuminatedWord = { bg = "#a8aecb" },
    lCursor = { bg = "#3760bf", fg = "#e1e2e7" },
    qfFileName = { bg = N, fg = "#2e7de9" },
    qfLineNr = { bg = N, fg = "#68709a" },
  }, {
    CurSearch = "IncSearch",
    Delimiter = "Special",
    FzfLuaCursor = "IncSearch",
    FzfLuaFilePart = "FzfLuaFzfNormal",
    FzfLuaFzfCursorLine = "Visual",
    FzfLuaHeaderText = "Title",
    FzfLuaPath = "Directory",
    LspKindColor = "Special",
    LspKindEvent = "Special",
    LspKindFile = "Normal",
    LspKindFolder = "Directory",
    LspKindSnippet = "Conceal",
    MiniAnimateNormalFloat = "NormalFloat",
    MiniClueBorder = "FloatBorder",
    MiniClueDescSingle = "NormalFloat",
    MiniClueTitle = "FloatTitle",
    MiniDepsChangeAdded = "diffAdded",
    MiniDepsChangeRemoved = "diffRemoved",
    MiniDepsHint = "DiagnosticHint",
    MiniDepsInfo = "DiagnosticInfo",
    MiniDepsMsgBreaking = "DiagnosticWarn",
    MiniDepsPlaceholder = "Comment",
    MiniDepsTitle = "Title",
    MiniDepsTitleSame = "Comment",
    MiniDiffOverAdd = "DiffAdd",
    MiniDiffOverChange = "DiffText",
    MiniDiffOverContext = "DiffChange",
    MiniDiffOverDelete = "DiffDelete",
    MiniFilesBorder = "FloatBorder",
    MiniFilesCursorLine = "CursorLine",
    MiniFilesDirectory = "Directory",
    MiniFilesNormal = "NormalFloat",
    MiniFilesTitle = "FloatTitle",
    MiniJump2dDim = "Comment",
    MiniMapNormal = "NormalFloat",
    MiniMapSymbolCount = "Special",
    MiniMapSymbolLine = "Title",
    MiniNotifyBorder = "FloatBorder",
    MiniNotifyNormal = "NormalFloat",
    MiniNotifyTitle = "FloatTitle",
    MiniOperatorsExchangeFrom = "IncSearch",
    MiniPickBorder = "FloatBorder",
    MiniPickIconDirectory = "Directory",
    MiniPickMatchCurrent = "CursorLine",
    MiniPickMatchMarked = "Visual",
    MiniPickNormal = "NormalFloat",
    MiniPickPreviewLine = "CursorLine",
    MiniPickPreviewRegion = "IncSearch",
    WinBar = "StatusLine",
    WinBarNC = "StatusLineNC",
  })
end
