cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #273141
selection_background  #bdc7dc
url_color             #a7c8ff

color0   #131313
color1   #e64c46
color2   #70d66e
color3   #dbd27b
color4   #5981c9
color5   #8a9ebf
color6   #a7c8ff
color7   #abb2bf
color8   #5c6370
color9   #e05f5f
color10  #87e086
color11  #e8e097
color12  #b2d6ff
color13  #4b7da6
color14  #6777af
color15  #ffffff
