-- Lazygit Theme Synchronizer for Neovim
-- Independent version that doesn't rely on tmux code

local M = {}

function M.reload_lazygit_instances()
  -- Method 1: Send 'R' key to reload (if lazygit supports it)
  local tmux_cmd = [[
    for pane in $(tmux list-panes -F '#{pane_id}:#{pane_current_command}' 2>/dev/null | grep lazygit | cut -d: -f1); do
      tmux send-keys -t "$pane" "R" 2>/dev/null
    done
  ]]
  os.execute(tmux_cmd)
  
  -- Method 2: Restart lazygit in tmux panes
  local restart_cmd = [[
    for pane in $(tmux list-panes -F '#{pane_id}:#{pane_current_command}' 2>/dev/null | grep lazygit | cut -d: -f1); do
      tmux send-keys -t "$pane" "q" 2>/dev/null
      sleep 0.5
      tmux send-keys -t "$pane" "lazygit" Enter 2>/dev/null
    done
  ]]
  os.execute(restart_cmd)
end

-- Configuração do tema lazygit
M.config = {
  config_path = os.getenv("HOME") .. "/.config/lazygit/config.yml",
  nerd_fonts_version = "3",
  -- Mapeamento de highlights do Neovim para cores do lazygit
  color_mapping = {
    active_border = { hl_group = "lualine_a_normal", attribute = "bg" },
    inactive_border = { hl_group = "CusrorLine", attribute = "bg" },
    options_text = { hl_group = "lualine_a_normal", attribute = "bg" },
    selected_line_bg = { hl_group = "lualine_b_normal", attribute = "bg" },
    cherry_picked_fg = { hl_group = "lualine_a_normal", attribute = "bg" },
    cherry_picked_bg = { hl_group = "Normal", attribute = "fg" },
    marked_commit_fg = { hl_group = "lualine_a_normal", attribute = "bg" },
    marked_commit_bg = { hl_group = "Normal", attribute = "fg" },
    default_fg = { hl_group = "Normal", attribute = "fg" },
  },
  -- Cores fixas que não mudam com o tema
  fixed_colors = {
    unstaged_changes = "#db4b4b",
  },
}

-- Função para extrair cores dos highlights do Neovim
function M.get_theme_colors()
  local function get_hl_value(hl_group, attribute)
    local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = hl_group })
    if not ok or not hl then
      return nil
    end
    return hl[attribute]
  end

  local function to_hex(color)
    if not color then
      return nil
    end

    -- Já é string hexadecimal
    if type(color) == "string" and color:match("^#%x+$") then
      return color
    end

    -- É número (decimal)
    if type(color) == "number" then
      return string.format("#%06x", color)
    end

    -- É tabela RGB
    if type(color) == "table" and color[1] and color[2] and color[3] then
      return string.format("#%02x%02x%02x", color[1], color[2], color[3])
    end

    return nil
  end

  local colors = {}

  -- Extrai cores baseadas no mapeamento
  for key, mapping in pairs(M.config.color_mapping) do
    local color_value = get_hl_value(mapping.hl_group, mapping.attribute)
    colors[key] = to_hex(color_value)
  end

  -- Fallbacks para cores não encontradas (baseado no tema Tokyo Night)
  colors.active_border = colors.active_border or "#7aa2f7"
  colors.inactive_border = colors.inactive_border or "#3b4261"
  colors.options_text = colors.options_text or "#7aa2f7"
  colors.selected_line_bg = colors.selected_line_bg or "#283457"
  colors.cherry_picked_fg = colors.cherry_picked_fg or "#7aa2f7"
  colors.cherry_picked_bg = colors.cherry_picked_bg or "#c0caf5"
  colors.marked_commit_fg = colors.marked_commit_fg or "#7aa2f7"
  colors.marked_commit_bg = colors.marked_commit_bg or "#c0caf5"
  colors.default_fg = colors.default_fg or "#c0caf5"

  return colors
end

-- Gera o conteúdo YAML para o tema do lazygit
function M.generate_lazygit_config()
  local colors = M.get_theme_colors()

  local yaml_content = {
    "# Lazygit theme generated automatically from Neovim colorscheme",
    "# Do not edit this file manually - it will be overwritten",
    "",
    "gui:",
    string.format('  nerdFontsVersion: "%s"', M.config.nerd_fonts_version),
    "  theme:",
    "    activeBorderColor:",
    string.format('      - "%s"', colors.active_border),
    '      - "bold"',
    string.format('    inactiveBorderColor: ["%s"]', colors.inactive_border),
    "    searchingActiveBorderColor:",
    string.format('      - "%s"', colors.active_border),
    '      - "bold"',
    string.format('    optionsTextColor: ["%s"]', colors.options_text),
    string.format('    selectedLineBgColor: ["%s"]', colors.selected_line_bg),
    string.format('    cherryPickedCommitFgColor: ["%s"]', colors.cherry_picked_fg),
    string.format('    cherryPickedCommitBgColor: ["%s"]', colors.cherry_picked_bg),
    string.format('    markedBaseCommitFgColor: ["%s"]', colors.marked_commit_fg),
    string.format('    markedBaseCommitBgColor: ["%s"]', colors.marked_commit_bg),
    string.format('    unstagedChangesColor: ["%s"]', M.config.fixed_colors.unstaged_changes),
    string.format('    defaultFgColor: ["%s"]', colors.default_fg),
    "",
  }

  return table.concat(yaml_content, "\n")
end

-- Escreve o arquivo de configuração do lazygit
function M.update_lazygit_theme()
  local config_content = M.generate_lazygit_config()
  local config_dir = os.getenv("HOME") .. "/.config/lazygit"

  -- Cria o diretório se não existir
  vim.fn.mkdir(config_dir, "p")

  local file = io.open(M.config.config_path, "w")
  if file then
    file:write(config_content)
    file:close()
    -- vim.notify("🎨 Lazygit theme updated!", vim.log.levels.INFO)
    M.reload_lazygit_instances()
    return true
  else
    vim.notify("❌ Failed to write lazygit theme config", vim.log.levels.ERROR)
    return false
  end
end

-- Configura os autocommands para sincronização automática
function M.setup()
  local lazygit_group = vim.api.nvim_create_augroup("LazygitThemeSync", { clear = true })

  -- Atualiza quando o colorscheme muda
  vim.api.nvim_create_autocmd("ColorScheme", {
    group = lazygit_group,
    pattern = "*",
    callback = function()
      vim.defer_fn(function()
        M.update_lazygit_theme()
      end, 100)
    end,
    desc = "Update Lazygit theme on colorscheme change",
  })

  -- Atualiza quando o background muda
  vim.api.nvim_create_autocmd("ColorScheme", {
    group = lazygit_group,
    pattern = "background",
    callback = function()
      vim.defer_fn(function()
        M.update_lazygit_theme()
      end, 100)
    end,
    desc = "Update Lazygit theme on background change",
  })

  -- Atualiza uma vez ao carregar o Neovim
  vim.defer_fn(function()
    M.update_lazygit_theme()
  end, 200)

  -- Adiciona comando do usuário
  vim.api.nvim_create_user_command("LazygitUpdateTheme", function()
    M.update_lazygit_theme()
  end, { desc = "Update Lazygit theme from current Neovim colorscheme" })

  -- Mapeamento de tecla opcional
  -- vim.keymap.set("n", "<leader>", "<cmd>LazygitUpdateTheme<cr>", { silent = true, desc = "Update Lazygit Theme" })

  -- vim.notify("🚀 Lazygit Theme Sync loaded! Theme will update automatically.")
end

M.setup()

-- Interface pública
return M
